// ─── V1 ABIs (live contracts — do not remove) ─────────────────────────────────

export const CAMPAIGN_FACTORY_ABI = [
  {
    type: "function",
    name: "cloneCampaign",
    inputs: [
      { name: "templateName", type: "string" },
      { name: "initData", type: "bytes" },
      { name: "creator", type: "address" },
    ],
    outputs: [{ name: "clone", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCampaigns",
    inputs: [],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCampaignCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorCampaigns",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setImplementation",
    inputs: [
      { name: "name", type: "string" },
      { name: "impl", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "campaignCreator",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "campaignTemplate",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CampaignCreated",
    inputs: [
      { name: "clone",        type: "address", indexed: true },
      { name: "creator",      type: "address", indexed: true },
      { name: "templateName", type: "string",  indexed: false },
    ],
  },
] as const;

export const PREDICTION_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_title", type: "string" },
      { name: "_options", type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitPrediction",
    inputs: [{ name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [
      { name: "", type: "string[]" },
      { name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserVoted",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserChoice",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PredictionSubmitted",
    inputs: [
      { name: "user",        type: "address", indexed: true },
      { name: "optionIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CampaignInitialized",
    inputs: [
      { name: "title",    type: "string",   indexed: false },
      { name: "options",  type: "string[]", indexed: false },
      { name: "deadline", type: "uint256",  indexed: false },
    ],
  },
] as const;

export const VOTING_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_title", type: "string" },
      { name: "_options", type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVote",
    inputs: [{ name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [
      { name: "", type: "string[]" },
      { name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserVoted",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserChoice",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "VoteCast",
    inputs: [
      { name: "user",        type: "address", indexed: true },
      { name: "optionIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VoteInitialized",
    inputs: [
      { name: "title",    type: "string",   indexed: false },
      { name: "options",  type: "string[]", indexed: false },
      { name: "deadline", type: "uint256",  indexed: false },
    ],
  },
] as const;

// ─── V2 ABIs ──────────────────────────────────────────────────────────────────

export const PREDICTION_LOGIC_V2_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",    type: "address" },
      { name: "_title",    type: "string" },
      { name: "_options",  type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitPrediction",
    inputs: [{ name: "voter", type: "address" }, { name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeCampaign",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealResult",
    inputs: [{ name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [
      { name: "", type: "string[]" },
      { name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserVoted",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserChoice",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isWinner",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWinner",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "winningOption",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CampaignInitialized",
    inputs: [
      { name: "title",    type: "string",   indexed: false },
      { name: "options",  type: "string[]", indexed: false },
      { name: "deadline", type: "uint256",  indexed: false },
    ],
  },
  {
    type: "event",
    name: "PredictionSubmitted",
    inputs: [
      { name: "user",        type: "address", indexed: true },
      { name: "optionIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CampaignClosed",
    inputs: [],
  },
  {
    type: "event",
    name: "ResultRevealed",
    inputs: [
      { name: "winningOption", type: "uint256", indexed: false },
    ],
  },
] as const;

export const VOTING_LOGIC_V2_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",    type: "address" },
      { name: "_title",    type: "string" },
      { name: "_options",  type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVote",
    inputs: [{ name: "voter", type: "address" }, { name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeCampaign",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [
      { name: "", type: "string[]" },
      { name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserVoted",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserChoice",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "VoteInitialized",
    inputs: [
      { name: "title",    type: "string",   indexed: false },
      { name: "options",  type: "string[]", indexed: false },
      { name: "deadline", type: "uint256",  indexed: false },
    ],
  },
  {
    type: "event",
    name: "VoteCast",
    inputs: [
      { name: "user",        type: "address", indexed: true },
      { name: "optionIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CampaignClosed",
    inputs: [],
  },
] as const;

export const SURVEY_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",   type: "address" },
      { name: "_title",   type: "string" },
      { name: "_options", type: "string[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitResponse",
    inputs: [{ name: "voter", type: "address" }, { name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeSurvey",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [
      { name: "", type: "string[]" },
      { name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserResponded",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserChoice",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SurveyInitialized",
    inputs: [
      { name: "title",   type: "string",   indexed: false },
      { name: "options", type: "string[]", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ResponseSubmitted",
    inputs: [
      { name: "user",        type: "address", indexed: true },
      { name: "optionIndex", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SurveyClosed",
    inputs: [],
  },
] as const;

// ─── Phase 1 ABIs ─────────────────────────────────────────────────────────────

export const QUIZ_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",    type: "address" },
      { name: "_title",    type: "string" },
      { name: "_options",  type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitAnswer",
    inputs: [{ name: "user", type: "address" }, { name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeCampaign",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revealAnswer",
    inputs: [{ name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [{ name: "", type: "string[]" }, { name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasUserAnswered",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserAnswer",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isCorrect",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCorrectOptionLabel",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "correctOption",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  {
    type: "event",
    name: "QuizInitialized",
    inputs: [
      { name: "title", type: "string", indexed: false },
      { name: "options", type: "string[]", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
    ],
  },
  { type: "event", name: "AnswerSubmitted", inputs: [{ name: "user", type: "address", indexed: true }, { name: "optionIndex", type: "uint256", indexed: false }] },
  { type: "event", name: "QuizClosed", inputs: [] },
  { type: "event", name: "AnswerRevealed", inputs: [{ name: "correctOption", type: "uint256", indexed: false }] },
] as const;

export const RAFFLE_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",            type: "address" },
      { name: "_title",            type: "string" },
      { name: "_prizeDescription", type: "string" },
      { name: "_deadline",         type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enter",
    inputs: [{ name: "participant", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "closeCampaign", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "selectWinner",  inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "getState",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  { type: "function", name: "getDeadline",       inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getParticipantCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "hasEntered",         inputs: [{ name: "participant", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "isWinner",           inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "winner",             inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "prizeDescription",   inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "RaffleInitialized",  inputs: [{ name: "title", type: "string", indexed: false }, { name: "prizeDescription", type: "string", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  { type: "event", name: "ParticipantEntered", inputs: [{ name: "participant", type: "address", indexed: true }] },
  { type: "event", name: "RaffleClosed",       inputs: [] },
  { type: "event", name: "WinnerSelected",     inputs: [{ name: "winner", type: "address", indexed: true }] },
] as const;

export const BOUNTY_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",                type: "address" },
      { name: "_title",                type: "string" },
      { name: "_challengeDescription", type: "string" },
      { name: "_deadline",             type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "register",
    inputs: [{ name: "participant", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "closeCampaign",    inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "finalizeWinners",
    inputs: [{ name: "_winners", type: "address[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "getState",           inputs: [], outputs: [{ name: "", type: "uint8" }],     stateMutability: "view" },
  { type: "function", name: "getDeadline",        inputs: [], outputs: [{ name: "", type: "uint256" }],   stateMutability: "view" },
  { type: "function", name: "getParticipantCount", inputs: [], outputs: [{ name: "", type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "hasRegistered",      inputs: [{ name: "participant", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getWinners",         inputs: [], outputs: [{ name: "", type: "address[]" }], stateMutability: "view" },
  { type: "function", name: "isWinner",           inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "challengeDescription", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "BountyInitialized",    inputs: [{ name: "title", type: "string", indexed: false }, { name: "challengeDescription", type: "string", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  { type: "event", name: "ParticipantRegistered", inputs: [{ name: "participant", type: "address", indexed: true }] },
  { type: "event", name: "BountyClosed",          inputs: [] },
  { type: "event", name: "WinnersFinalized",      inputs: [{ name: "winners", type: "address[]", indexed: false }] },
] as const;

export const FAN_PASS_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",           type: "address" },
      { name: "_title",           type: "string" },
      { name: "_tierNames",       type: "string[]" },
      { name: "_tierMaxSupplies", type: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPass",
    inputs: [{ name: "holder", type: "address" }, { name: "tierIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "closeEvent",   inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getState",     inputs: [], outputs: [{ name: "", type: "uint8" }],   stateMutability: "view" },
  { type: "function", name: "getTierCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "getTier",
    inputs: [{ name: "tierIndex", type: "uint256" }],
    outputs: [{ name: "name", type: "string" }, { name: "maxSupply", type: "uint256" }, { name: "issued", type: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "hasClaimed",         inputs: [{ name: "holder", type: "address" }, { name: "tierIndex", type: "uint256" }], outputs: [{ name: "", type: "bool" }],      stateMutability: "view" },
  { type: "function", name: "getHolderPasses",    inputs: [{ name: "holder", type: "address" }], outputs: [{ name: "", type: "uint256[]" }], stateMutability: "view" },
  { type: "function", name: "getTierHolders",     inputs: [{ name: "tierIndex", type: "uint256" }], outputs: [{ name: "", type: "address[]" }], stateMutability: "view" },
  { type: "function", name: "getTierHolderCount", inputs: [{ name: "tierIndex", type: "uint256" }], outputs: [{ name: "", type: "uint256" }],   stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "FanPassInitialized", inputs: [{ name: "title", type: "string", indexed: false }, { name: "tierCount", type: "uint256", indexed: false }] },
  { type: "event", name: "PassClaimed",        inputs: [{ name: "holder", type: "address", indexed: true }, { name: "tierIndex", type: "uint256", indexed: true }, { name: "tierName", type: "string", indexed: false }] },
  { type: "event", name: "EventClosed",        inputs: [] },
] as const;

export const POINTS_POOL_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",    type: "address" },
      { name: "_title",    type: "string" },
      { name: "_options",  type: "string[]" },
      { name: "_deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stakeWeight",
    inputs: [{ name: "user", type: "address" }, { name: "optionIndex", type: "uint256" }, { name: "weight", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "closeCampaign", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "revealResult",
    inputs: [{ name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getResults",
    inputs: [],
    outputs: [{ name: "", type: "string[]" }, { name: "", type: "uint256[]" }, { name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  { type: "function", name: "getDeadline",  inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getState",     inputs: [], outputs: [{ name: "", type: "uint8" }],   stateMutability: "view" },
  { type: "function", name: "hasPredicted", inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  {
    type: "function",
    name: "getUserPrediction",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "optionIndex", type: "uint256" }, { name: "weight", type: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "isCorrect",     inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getWinnerLabel", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "winningOption",  inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "PoolInitialized",  inputs: [{ name: "title", type: "string", indexed: false }, { name: "options", type: "string[]", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  { type: "event", name: "PredictionStaked", inputs: [{ name: "user", type: "address", indexed: true }, { name: "optionIndex", type: "uint256", indexed: false }, { name: "weight", type: "uint256", indexed: false }] },
  { type: "event", name: "PoolClosed",       inputs: [] },
  { type: "event", name: "ResultRevealed",   inputs: [{ name: "winningOption", type: "uint256", indexed: false }] },
] as const;

export const TOURNAMENT_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "_owner", type: "address" }, { name: "_title", type: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addRound",
    inputs: [{ name: "_description", type: "string" }, { name: "_options", type: "string[]" }, { name: "_deadline", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitPrediction",
    inputs: [{ name: "user", type: "address" }, { name: "roundIndex", type: "uint256" }, { name: "optionIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeRound",
    inputs: [{ name: "roundIndex", type: "uint256" }, { name: "correctOption", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRoundScore",
    inputs: [{ name: "user", type: "address" }, { name: "roundIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "completeTournament", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getState",     inputs: [], outputs: [{ name: "", type: "uint8" }],   stateMutability: "view" },
  { type: "function", name: "getRoundCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "getRound",
    inputs: [{ name: "roundIndex", type: "uint256" }],
    outputs: [
      { name: "description",  type: "string" },
      { name: "options",      type: "string[]" },
      { name: "deadline",     type: "uint256" },
      { name: "finalized",    type: "bool" },
      { name: "correctOption", type: "uint256" },
      { name: "voteCounts",   type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "hasPredictedRound",  inputs: [{ name: "user", type: "address" }, { name: "roundIndex", type: "uint256" }], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "getRoundPrediction", inputs: [{ name: "user", type: "address" }, { name: "roundIndex", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getScore",           inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "currentRound", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "TournamentInitialized", inputs: [{ name: "title", type: "string", indexed: false }] },
  { type: "event", name: "RoundAdded",          inputs: [{ name: "roundIndex", type: "uint256", indexed: false }, { name: "description", type: "string", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  { type: "event", name: "PredictionSubmitted", inputs: [{ name: "user", type: "address", indexed: true }, { name: "roundIndex", type: "uint256", indexed: false }, { name: "optionIndex", type: "uint256", indexed: false }] },
  { type: "event", name: "RoundFinalized",      inputs: [{ name: "roundIndex", type: "uint256", indexed: false }, { name: "correctOption", type: "uint256", indexed: false }] },
  { type: "event", name: "TournamentCompleted", inputs: [] },
] as const;

export const AUCTION_LOGIC_ABI = [
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner",                type: "address" },
      { name: "_title",                type: "string" },
      { name: "_privilegeDescription", type: "string" },
      { name: "_deadline",             type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "placeBid",
    inputs: [{ name: "bidder", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "closeCampaign", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "selectWinner",
    inputs: [{ name: "_winner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "getState",      inputs: [], outputs: [{ name: "", type: "uint8" }],   stateMutability: "view" },
  { type: "function", name: "getDeadline",   inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getBidderCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "getBid",
    inputs: [{ name: "bidder", type: "address" }],
    outputs: [{ name: "amount", type: "uint256" }, { name: "timestamp", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHighestBid",
    inputs: [],
    outputs: [{ name: "topBidder", type: "address" }, { name: "topAmount", type: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "isWinner",            inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "winner",              inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "winningBid",          inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "privilegeDescription", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "title", inputs: [], outputs: [{ name: "", type: "string" }],  stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "AuctionInitialized", inputs: [{ name: "title", type: "string", indexed: false }, { name: "privilegeDescription", type: "string", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  { type: "event", name: "BidPlaced",    inputs: [{ name: "bidder", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }] },
  { type: "event", name: "BidUpdated",   inputs: [{ name: "bidder", type: "address", indexed: true }, { name: "oldAmount", type: "uint256", indexed: false }, { name: "newAmount", type: "uint256", indexed: false }] },
  { type: "event", name: "AuctionClosed", inputs: [] },
  { type: "event", name: "WinnerSelected", inputs: [{ name: "winner", type: "address", indexed: true }, { name: "winningBid", type: "uint256", indexed: false }] },
] as const;

